CXX = g++
CXXFLAGS = -std=c++17 -O2 -pthread

# target to build problem3

problem3:
	$(CXX) $(CXXFLAGS) -o problem3.exe problem3_dir/210874.cpp problem3_dir/210874.h

# clean rule to delete executables
clean:
	rm -f problem3.exe
